// frontend-react/src/components/OutstandingNumbers.tsx
import React from 'react';

const stats = [
  { label: "Số năm kinh nghiệm", value: "10+" },
  { label: "Khách hàng quốc tế", value: "500+" },
  { label: "Dự án thành công", value: "1000+" },
  { label: "Văn phòng và chi nhánh", value: "10" },
  { label: "Top công ty Công nghệ tại Việt Nam", value: "Top 3" },
  { label: "Tỷ lệ khách hàng hài lòng", value: "97%" },
];

const partners = [
  { name: "U.S.M.Holdings", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788295/c92c18b7-4b09-46a3-8963-173fd8e0a4d1.png" },
  { name: "Studio NE63", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788332/4990ea56-793d-4f88-8d5e-5c3d2a646a8a.png" },
  { name: "Sunloft", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788355/f2a65825-796e-4703-b57a-3f30377e0f73.png" },
  { name: "Systena", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788440/7cf2f34e-d79e-4874-8b74-060d4ce77612.png" },
  { name: "Fujikin", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788448/ef2f6070-6040-4f91-8e38-5b103d3bbdec.png" },
  { name: "Cloud", logo: "https://res.cloudinary.com/djppquc7s/image/upload/v1775788452/86d1cf22-6a88-4338-b415-f1d573f00509.png" },
];

const OutstandingNumbers: React.FC = () => {
  return (
    <div className="bg-gray-50 pt-16">
      {/* Stats Section */}
      <section 
        className="py-20 relative overflow-hidden" 
        style={{ backgroundColor: '#bc2228' }}
      >
        {/* Subtle Background Pattern */}
        <div className="absolute inset-0 opacity-10 pointer-events-none">
          <svg className="h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none">
            <path d="M0 100 L100 0 L100 100 Z" fill="black" />
          </svg>
        </div>

        <div className="max-w-7xl mx-auto px-4 relative z-10">
          <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-12 text-center">
            Tại sao chọn chúng tôi?
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {stats.map((stat, index) => (
              <div
                key={index}
                className="bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20 transform hover:-translate-y-2 transition-all duration-300"
              >
                <p className="text-white/70 text-sm mb-2 font-medium uppercase tracking-wider">{stat.label}</p>
                <p className="text-white text-5xl font-extrabold">{stat.value}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Partners Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-extrabold text-gray-900 mb-12">Đối tác tuyển dụng</h2>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-8 items-center justify-items-center">
            {partners.map((partner, index) => (
              <div
                key={index}
                className="p-4 grayscale hover:grayscale-0 opacity-60 hover:opacity-100 transition-all duration-500 transform hover:scale-110"
              >
                <img
                  loading="lazy"
                  src={partner.logo}
                  alt={partner.name}
                  className="max-h-12 w-auto object-contain"
                />
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default OutstandingNumbers;

// frontend/src/views/home/Outstandingnumbers.vue
<template>
  <div>
    <section
      class="py-16 dark:bg-red-800"
      style="
        background-image: url('background-image');
      "
    >
      <div class="max-w-7xl mx-auto px-4">
        <h2 class="text-3xl font-bold text-white mb-12">
          Tại sao chọn chúng tôi?
        </h2>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div
            v-for="(stat, index) in stats"
            :key="index"
            v-scroll-reveal="{ delay: 200 }"
            class="bg-white rounded-lg p-6 transform hover:-translate-y-1 transition-transform duration-300"
          >
            <p class="text-gray-600 text-sm mb-2">{{ stat.label }}</p>
            <p class="text-red-600 text-4xl font-bold">{{ stat.value }}</p>
          </div>
        </div>
      </div>
    </section>

    <section class="py-16 bg-white">
      <div class="max-w-7xl mx-auto px-4">
        <h2 class="text-3xl font-bold text-center mb-12">Đối tác tuyển dụng</h2>

        <div
          class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 sm:gap-6 lg:gap-8"
        >
          <div
            v-for="(partner, index) in partners"
            :key="index"
            class="p-4 flex items-center justify-center hover:opacity-75 transition-opacity duration-300"
          >
            <img
              loading="lazy"
              :src="partner.logo"
              :alt="partner.name"
              class="max-h-12 w-auto"
            />
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref } from "vue";

const stats = ref([
  {
    label: "Số năm kinh nghiệm",
    value: "10+",
  },
  {
    label: "Khách hàng quốc tế",
    value: "500+",
  },
  {
    label: "Dự án thành công",
    value: "1000+",
  },
  {
    label: "Văn phòng và chi nhánh",
    value: "10",
  },
  {
    label: "Top công ty Công nghệ tại Việt Nam",
    value: "Top 3",
  },
  {
    label: "Tỷ lệ khách hàng hài lòng",
    value: "97%",
  },
]);

const partners = ref([
  {
    name: "U.S.M.Holdings",
    logo: "https://s3-alpha-sig.figma.com/img/ba9b/90af/a95d4df69f56c7044cceaf8db38c3401?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=D88P86RbdMYaVP46lvSf7i7Ogm4KySN7VA5yWdynjohfyZ5L6Ha1oOPTMlebqalR3qfEVy9H~PJaFG-WlIejGrn1K-smQ6TXahIR9i1QJEa2zb1~0kjqC0e-PedF7Hmf6P5NxmkFjdpgYZsTqSIt9EBsGN7TN5XeVytZB6Hm-RxwqrMrMvQfJWoOoHOYte-fl5YqU9vJeZTjYVgiEK8kjb095ULJ30t6QBmJ3joJc29DpIaEaLDwMubSMYH8Q6FFkc9W3Sz2Nq8aUsI8s~WY-l3hwXntQMURJaZ2RtxsjRFzhFAVLNYt3JiTLolkojNHSHhphxh-n0e2QLpH2GFJ4A__",
  },
  {
    name: "Studio NE63",
    logo: "https://s3-alpha-sig.figma.com/img/99c1/4e9b/eaedef77670568d349ccd38810aca795?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=oDGi11vkCOYFeUtbmvTNDPwpyLxw8rJ9nyepPjYzoqss11Cj1nyO0lEnYxKpHg5qk-vJDUyXYZxtfAV6qaNt28nxzCtJr1oVyeXrxM-O32azxe-ZLB9Wc~2i0LctKgXdC5E0JeWky3FVfoPXzdcSsfZhqUjzIM2VWjliLpv0CaIDDlUZxNL21X3EadUpxsCc3QrT-eYlebVmz1Dlz7QdSf0FwU6bMyKYhQufgfdWK5ny69TLTrIHSY6bO6dvl8L19cNsA63YH4zRDwirx~0TCmeBGSHuBi5A2KGtl2dpxUKRM9WotcJrM-u7UjK61RtEq~ExcIyZDKY7Sq4pWfxmog__",
  },
  {
    name: "Sunloft",
    logo: "https://s3-alpha-sig.figma.com/img/62fb/741d/1029c644481ff6fdb28b781bad3418cc?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=ji75aB~uBB9Ba7KuAut6gPZJJ4b-wEVG62m87gQGrZqDI2YDChJvtU77XmAjsTnXmW-UFZ~K-YT9t59bcIZ5FOdfLjn-M2Sq9u~wnK3XY7FJ1qldjTpKxjhT9T7sVFqWwMv7pBAWbC4JOYLJ2NoP1yenyglTyk-u2tT0zlVXX-FJyCdyE6b2lZhxfU-O3oa1DCA6R~IWulLJoOVE87WNBC896qSLppT4K6NHrWkvVePrTx-doc7XiSpVH6NwTVnjbs-Va6-FvFf-0lDX8KbwP7cBfIjmei5r06EdrK~UibGRiA~YVbkgdwHcnNqLeVxjWNXN~qIuaPhNzU9OgbxSBA__",
  },
  {
    name: "Systena",
    logo: "https://s3-alpha-sig.figma.com/img/e5a7/d176/dccc4222da4aeb757c467033bca0f3c6?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=DsTjaDOLpuZ4kQPFSmEzZ04NcbbQdsIjulLzFiT57YVR-lKZUzKm1SwAYzVsqFwYK6dwvmLc2KjRB24Y4xtHPqigwoYAEmMICMgCrpTeqiUGgSUR0UwRDY9X5YkC1LZIHv6AGjq6smeJ3XPJdmBRh0rAGfcGko6vdmuybgD2uUH1NQznAAU1qc~RabKmkULvcv9-U~Z8CvOLjuBJ0udpVMHs4oQ3Vwm5VIDEFgGAQ1u4PgGQuwC6mB4ms0VRztZJvPnJaSVXgt2oPs65JFFlN~0b5o~CTAOlEkJoW7p~nMnsmgpq1o86Gg9SjDy53I3b8Iv0QWx9C6TGqXpnF9bNsQ__",
  },
  {
    name: "Fujikin",
    logo: "https://s3-alpha-sig.figma.com/img/9e4f/caef/a8d37d5d334caf03894ca555fa238a0f?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=eQZGP95iIzhIiiND39iP1tA32dOdsvT-617f9TAA4CQUvrT799irt9wJtoj7p0MqtbyDUvWDdv21l83mY0ZkB-yzvtXG3-aXruEw4f6jqPcgMS5weedBirQnqUIY6b9HtJa25at~faE02bQAMvTq6sD5YHxJfaCl~xT9dyBpTOl3OzCB2XnK-ReyPIewiVSmkeiGS0Q9WlCul8u70Rf6bYn84f52Mol8gWbym-BzQCn826BidE0KYbQmHAJEVZjWg58znnRrGevF1fVkRL6WWpcEHoBqAoPYQdqEVvo1xEGzW8ZjyQC0ejgWSQqLHTOItDMNs73PCp9j6dIPCDBFSg__",
  },
  {
    name: "Cloud",
    logo: "https://s3-alpha-sig.figma.com/img/ba03/88f8/fae8c5e33ba402f5160697ee16424570?Expires=1733097600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=iBYfXzKqJ0WvJ3GIfzg5jWUu46GJIw0P-9F0fkvpR8p36WJF2W0uemEUr36TbjOSNLiDJD~vwOooOKAzQsq4hKTjaUUoUzwjhTYcBu7CFTJxFaoJLxioKBa3QJUytFLbb00YZitvZ9R2EJNfQa08bARAp2N8LmlJL8Rq5nVnt3U2xjip0IbrSyh8HQhTBSGUppVoMV1ObA~v5NrOrMdK28FIC~KxyNPpd-qqwWwsqjwTr4tris~k6A02sJk5syR-j6SE1domn2Qo3DtA3lEqiRBgbnqRSEJvLI~ZUNxNb3fTRdcPoMtOIaeP426FUuM1tDjgWks5Ca9WJ6QA9VYX3A__",
  },
]);
</script>

<style scoped></style>
