// frontend-react/src/pages/client/misc/AboutUs.tsx
import React from 'react';

export default function AboutUs() {
  return (
    <div>
      {/* Banner Section */}
      <div className="relative h-[435px] flex items-center justify-center text-white">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: "url('https://res-console.cloudinary.com/djppquc7s/thumbnails/v1/image/upload/v1766996354/QmFubmVySmJMaXN0X2t3N2Y4MQ==/drilldown')",
            backgroundPosition: "cover",
            backgroundSize: "100% 260%",
          }}
        ></div>

        <div
          style={{
            background: "linear-gradient(rgba(19, 12, 45, 1), rgba(35, 22, 81, 1), rgba(35, 22, 81, 1), rgba(19, 12, 45, 1))"
          }}
          className="absolute inset-0 opacity-50"
        ></div>

        {/* Banner Content */}
        <div className="relative flex flex-col items-center justify-center w-full z-10 mt-[10px]">
          <h1 className="text-white text-5xl font-bold mb-4 font-sf-pro-display">
            Về chúng tôi
          </h1>
          <p className="text-lg text-white font-sf-pro-display tracking-wide">
            Rikkeisoft - Top 3 Doanh nghiệp CNTT tại Việt Nam
          </p>
        </div>
      </div>

      {/* Intro Section */}
      <div className="max-w-7xl mx-auto px-6 py-20 relative overflow-hidden">
        <div className="flex flex-col lg:flex-row gap-[126px] items-center">
          <div className="flex-1 flex flex-col gap-6">
            <div>
              <h2 className="font-bold text-4xl mb-2 text-gray-900 font-sf-pro-display uppercase">
                Công ty cổ phần Rikkeisoft
              </h2>
              <p className="text-[#a5a500] text-lg font-medium font-sf-pro-display">
                Top 3 Doanh nghiệp CNTT tại Việt Nam
              </p>
            </div>
            <div className="text-gray-700 leading-relaxed font-sf-pro-display text-lg text-justify">
              <p>
                Thành lập năm 2012, Rikkeisoft đã trở thành một trong những doanh
                nghiệp công nghệ hàng đầu tại Việt Nam và Nhật Bản với gần 2.000
                thành viên. Bằng việc cung cấp các giải pháp công nghệ toàn diện
                như AI, Robotics, Blockchain và chuyển đổi số, Rikkeisoft đang góp
                phần nâng cao năng lực cạnh tranh của doanh nghiệp Việt trên
                trường quốc tế. Hiện tại Rikkeisoft đã hiện diện tại nhiều quốc
                gia trên thế giới như Mỹ, Nhật Bản, Singapore, Hàn Quốc và Thái
                Lan, ... góp phần đưa công nghệ Việt Nam vươn tầm quốc tế.
              </p>
            </div>
          </div>
          <div className="flex-1">
            <img
              className="rounded-xl shadow-xl w-full object-cover"
              src="https://s3-alpha-sig.figma.com/img/d9bd/6398/25319407681a7e926336fefb98d451aa?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=KmSF6hLrKh1LbMXrj5uW9hG5FRi8jHRodXbxa~K5IXWfhWaHrAvwyuQKBhH4xkTi3qhOEFvWaamRXwGx9mtTUB-puKZN8EaF9pO4aDYW~Rz67pyWUUlYk98HCscuwBcoO7Z5lwquIzbbEjWNL76jrNppXpT-lvUOxJfv2ryGgjcoyhkLY2Dosm2ilw5nqFw46Q3~UtBXtRXQt6O924f1BNVVZa-vt3QcXDpmbopjZYss~3IC2EMZZXf5prXPIre7mPztVLoEMf29IYYDfsuLIc~~J2LtnEFjZld5VoiWSbB5sqGT3mtDP~wf7t2I4m9h~6F~buGPs0ffXG-wrtUEqw__"
              alt="Rikkeisoft Office"
            />
          </div>
        </div>
        <img
          className="absolute top-[20%] left-[-10%] opacity-20 pointer-events-none z-[-1]"
          src="/src/assets/banner/decor4.svg"
          alt=""
        />
      </div>

      {/* Stats Section */}
      <div
        className="w-full py-20 bg-cover bg-center"
        style={{
          backgroundImage: "url('https://s3-alpha-sig.figma.com/img/2250/f891/827ff07cd21ae1be104e11e1b601b7c4?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=HzjzOBjApatjZmobKjNxInRcD22XEeg4phb6mI78-p2ZqOv7J4tOkfMo8qF3mhnnTpUXMtFGj8-TE3R7w8akpjAlkHPCuVX6BOf5uffSE2JGv7nzXEsmW8~kDFg9Nut4khWPrGjMHF45nt-OUP6BY2j4PTeb7vrCde71BVATDBXbIttDAH5o~lJNOXkRDd-higN8Dk50SpsK9nxqHciZXI2iMJgxMjateokTX73EwXb7cL4bqdx6qrix4f6V9DLduWz0yB3iDtpoqEmGKa7NWned0DL3F83b9jjRiTefNEAw1cHiIYgnzk0PKOKZpzSRZFdxbP63uKF-ZU4H~yXoiw__')"
        }}
      >
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider">
              Số lượng nhân viên
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">
              2000
            </p>
          </div>
          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider">
              Dự án đã thực hiện
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">
              1000
            </p>
          </div>
          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider">
              Khách hàng
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">
              500+
            </p>
          </div>

          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider">
              Số năm kinh nghiệm
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">12</p>
          </div>
          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider text-sm">
              VP đại diện tại các thành phố
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">10</p>
          </div>
          <div className="bg-gray-50 bg-opacity-95 p-8 rounded-xl shadow-md transform hover:-translate-y-1 transition duration-300">
            <p className="text-gray-600 font-semibold mb-2 font-sf-pro-display uppercase tracking-wider text-sm">
              Tỷ lệ giữ chân khách hàng
            </p>
            <p className="text-5xl text-[#bc2228] font-bold font-sf-pro-display">97%</p>
          </div>
        </div>
      </div>

      {/* Office Locations */}
      <div className="max-w-7xl mx-auto py-20 px-6 flex flex-col items-center">
        <h2 className="text-4xl text-gray-900 font-bold mb-12 font-sf-pro-display text-center uppercase tracking-wide">
          Văn phòng đại diện
        </h2>
        <div className="w-full">
          <img
            className="w-full object-cover rounded-xl shadow-lg"
            src="https://s3-alpha-sig.figma.com/img/ff9e/c123/c0debbfa7fba284175b53bd9990a8f9c?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=WxdfV4s7al82K-H6NZZB~HJBstRgtf4aczyYbOChlx2AzwMnOre4NGI086ZTLXwRZRt5iim3HquWb76cxa~oB61rQFEHCKlShi4ZQPS3m1BJ0Qn-SbGT~xXZsHE2qCx-zOrXvB-Ch2LVSb47Pr0ZSDObF~w0n8tij0x4~Oe-QsSnRzV6jIvTmUtDxjE83nr9R~m43pVrP9Pbw-ky-Jch8Yt0PtiAc1Vh6tYxLZj7AaaUta3eHwUIA370g-rfJ~WmRboIBMBxroDZqAkZkxXO-RPrTom7XC1qrKQALJgTrYaJQr2-pTLLb07oBq8ku3I550jPU9fGEn2W2VD4MiIJbw__"
            alt="Office Locations Map"
          />
        </div>
      </div>

      {/* Ecosystem Section */}
      <div className="w-full py-20 relative overflow-hidden bg-gray-50">
        <div className="max-w-7xl mx-auto px-6 text-center mb-16 relative z-10">
          <h2 className="text-gray-900 text-4xl font-bold font-sf-pro-display uppercase tracking-[0.1em]">
            Hệ sinh thái Rikkeisoft
          </h2>
        </div>

        <div className="relative flex justify-center items-center w-full min-h-[500px]">
          <img
            src="/src/assets/rk/rk.svg"
            alt="Rikkei Main Ecosystem"
            className="relative z-10 max-w-full h-auto drop-shadow-xl"
            style={{ width: '80%', maxWidth: '1200px' }}
          />
        </div>

        <img
          src="/src/assets/rk/dc.svg"
          alt="Decor"
          className="absolute top-0 right-0 z-0 opacity-30 pointer-events-none"
        />
      </div>
    </div>
  );
}

// frontend/src/layout/AboutUs.vue
<template>
  <div>
    <Header />
    <div class="relative h-[435px] flex items-center justify-center text-white">
      <div
        class="absolute inset-0 bg-cover bg-center image-banner"
        style="
          background-image: url('https://res-console.cloudinary.com/djppquc7s/thumbnails/v1/image/upload/v1766996354/QmFubmVySmJMaXN0X2t3N2Y4MQ==/drilldown');
          background-position: cover;
          background-size: 100% 260%;
          /* height: 100%; */
        "
      ></div>

      <div
        style="
          background: linear-gradient(
            rgba(19, 12, 45, 1),
            rgba(35, 22, 81, 1),
            rgba(35, 22, 81, 1),
            rgba(19, 12, 45, 1)
          );
        "
        class="absolute inset-0 opacity-50"
      ></div>

      <!-- Nội dung phía trước -->
      <div
        class="relative flex flex-col w-[341px] h-[76px] gap-[4px] mt-[10px]"
      >
        <div>
          <p
            class="text-[rgba(255,255,255,1)] text-[40px] h-[48px] font-bold flex justify-center mb-3"
          >
            Về chúng tôi
          </p>
          <p class="h-[24px] text-[16px] text-[rgba(255,255,255,1)] mb-0">
            Rikkeisoft - Top 3 Doanh nghiệp CNTT tại Việt Nam
          </p>
        </div>
      </div>
    </div>
    <div class="w-[1440px] h-[474px] pt-60 pr-120 pb-80 pl-120">
      <div class="flex gap-[126px]">
        <div class="w-[486px] h-[288px] gap-[24px] flex flex-col">
          <div class="w-[473px] h-[72px] gap-[4px]">
            <p
              class="w-[473px] h-[40px] font-bold text-[32px] mb-1 text-[rgba(17,17,17,1)]"
            >
              CÔNG TY CỔ PHẦN RIKKEISOFT
            </p>
            <p class="w-[296px] h-[28px] text-[rgba(80,80,0,1)]">
              Top 3 Doanh nghiệp CNTT tại Việt Nam
            </p>
          </div>
          <div class="w-[481] h-[192px]">
            <p class="text-[rgba(80,80,0,1)] mb-0">
              Thành lập năm 2012, Rikkeisoft đã trở thành một trong những doanh
              nghiệp công nghệ hàng đầu tại Việt Nam và Nhật Bản với gần 2.000
              thành viên. Bằng việc cung cấp các giải pháp công nghệ toàn diện
              như AI, Robotics, Blockchain và chuyển đổi số, Rikkeisoft đang góp
              phần nâng cao năng lực cạnh tranh của doanh nghiệp Việt trên
              trường quốc tế. Hiện tại Rikkeisoft đã hiện diện tại nhiều quốc
              gia trên thế giới như Mỹ, Nhật Bản, Singapore, Hàn Quốc và Thái
              Lan, ... góp phần đưa công nghệ Việt Nam vươn tầm quốc tế.
            </p>
          </div>
        </div>
        <div class="w-[584px] h-[388px]">
          <img
            class="rounded-md h-[338px]"
            src="https://s3-alpha-sig.figma.com/img/d9bd/6398/25319407681a7e926336fefb98d451aa?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=KmSF6hLrKh1LbMXrj5uW9hG5FRi8jHRodXbxa~K5IXWfhWaHrAvwyuQKBhH4xkTi3qhOEFvWaamRXwGx9mtTUB-puKZN8EaF9pO4aDYW~Rz67pyWUUlYk98HCscuwBcoO7Z5lwquIzbbEjWNL76jrNppXpT-lvUOxJfv2ryGgjcoyhkLY2Dosm2ilw5nqFw46Q3~UtBXtRXQt6O924f1BNVVZa-vt3QcXDpmbopjZYss~3IC2EMZZXf5prXPIre7mPztVLoEMf29IYYDfsuLIc~~J2LtnEFjZld5VoiWSbB5sqGT3mtDP~wf7t2I4m9h~6F~buGPs0ffXG-wrtUEqw__"
            alt=""
          />
        </div>
      </div>
      <img
        class="absolute top-[650px] left-0 z-[-1]"
        src="../assets/banner/decor4.svg"
        alt=""
      />
    </div>
    <div
      class="w-full h-[408px]"
      style="
        background-image: url('https://s3-alpha-sig.figma.com/img/2250/f891/827ff07cd21ae1be104e11e1b601b7c4?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=HzjzOBjApatjZmobKjNxInRcD22XEeg4phb6mI78-p2ZqOv7J4tOkfMo8qF3mhnnTpUXMtFGj8-TE3R7w8akpjAlkHPCuVX6BOf5uffSE2JGv7nzXEsmW8~kDFg9Nut4khWPrGjMHF45nt-OUP6BY2j4PTeb7vrCde71BVATDBXbIttDAH5o~lJNOXkRDd-higN8Dk50SpsK9nxqHciZXI2iMJgxMjateokTX73EwXb7cL4bqdx6qrix4f6V9DLduWz0yB3iDtpoqEmGKa7NWned0DL3F83b9jjRiTefNEAw1cHiIYgnzk0PKOKZpzSRZFdxbP63uKF-ZU4H~yXoiw__');
      "
    >
      <div
        class="relative w-[1200px] h-[108px] flex top-[80px] left-[120px] gap-[34px]"
      >
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold mt-0">
            Số lượng nhân viên
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">
            2000
          </p>
        </div>
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold">
            Dự án đã thực hiện
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">
            1000
          </p>
        </div>
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold">
            Khách hàng
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">
            500+
          </p>
        </div>
      </div>
      <div
        class="relative w-[1200px] h-[108px] flex top-[120px] left-[120px] gap-[34px]"
      >
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold">
            Số năm kinh nghiệm
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">12</p>
        </div>
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold">
            Văn phòng đại diện tại các thành phố
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">10</p>
        </div>
        <div
          class="w-[379px] h-[108px] bg-[rgba(250,250,250,1)] px-[24px] py-[12px] rounded-md"
        >
          <b class="text-[16px] text-[rgba(80,80,80,1)] font-semibold">
            Tỷ lệ giữ chân khách hàng
          </b>
          <p class="text-[48px] text-[rgba(188,34,40,1)] font-bold mb-0">97%</p>
        </div>
      </div>
    </div>
    <div class="w-full h-[892px] px-[200px] py-[80px] gap-[48px] flex flex-col">
      <div class="flex justify-center">
        <b
          class="w-[322px] h-[40xp] text-[32px] text-[rgba(17,17,17,1)] font-bold"
          >Văn phòng đại diện</b
        >
      </div>
      <div>
        <img
          class="w-[1024px] h-[644px]"
          src="https://s3-alpha-sig.figma.com/img/ff9e/c123/c0debbfa7fba284175b53bd9990a8f9c?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=WxdfV4s7al82K-H6NZZB~HJBstRgtf4aczyYbOChlx2AzwMnOre4NGI086ZTLXwRZRt5iim3HquWb76cxa~oB61rQFEHCKlShi4ZQPS3m1BJ0Qn-SbGT~xXZsHE2qCx-zOrXvB-Ch2LVSb47Pr0ZSDObF~w0n8tij0x4~Oe-QsSnRzV6jIvTmUtDxjE83nr9R~m43pVrP9Pbw-ky-Jch8Yt0PtiAc1Vh6tYxLZj7AaaUta3eHwUIA370g-rfJ~WmRboIBMBxroDZqAkZkxXO-RPrTom7XC1qrKQALJgTrYaJQr2-pTLLb07oBq8ku3I550jPU9fGEn2W2VD4MiIJbw__"
          alt=""
        />
      </div>
    </div>
    <div class="w-full h-[921px] relative">
      <div class="w-[1300px] h-[40px] mt-[84px] ml-[120px] flex justify-center">
        <b class="text-[rgba(17,17,17,1)] text-[32px] mb-0 font-bold"
          >HỆ SINH THÁI RIKKEISOFT</b
        >
      </div>
      <div>
        <div class="main-logo">
          <img src="../assets/rk/rk.svg" alt="Rikkei Main Logo" />
        </div>
      </div>
      <div class="absolute top-0 right-0 z-[-1]">
        <img src="../assets/rk/dc.svg" alt="" />
      </div>
    </div>
    <Footer />
  </div>
</template>

<script setup>
import Header from "./Header.vue";
import Footer from "./Footer.vue";
</script>

<style scoped>
/* .image-banner {
  background-image: linear-gradient(
      to bottom,
      rgba(25, 16, 58, 0.6) rgba(25, 16, 58, 0.5)
    ),
    url("https://s3-alpha-sig.figma.com/img/b0b8/1555/5aa35e46a32f52c6f849aeb687067af2?Expires=1732492800&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=R9gdzCvLDumgeInrUkhxqa41LU8y3fFk-S8lKtfXePV2nNpAxnfX3Jr48p91WJKkrF9tXQJ7maIprX19UCTWFu7a~uFaJkgqiMjqSmJUviF3GzSPJIHOiJf9aLHDPZryrTg59KDVwiUurQL2s8GuJ2VucQJxHYOkbvD96wwa2gpyWupxYalX9YKsNpT5TgRukl4Be~-fDOlkarCdLy2qCAZL6NaIeymPWv29vQe8Cz2H45mK7deTK5qpWweLImdAF2hoAc6hwXgB4Bdty4fU1dFvhFK-iGBpn5ZdzjzxTfXi~bpOYsftgPv47DF50TZpvLn3YZEL2R44oEjKKcKK6g__");
} */

.title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 20px;
  color: #333;
}

.main-logo {
  position: absolute;
  transform: translate(15%, 20%);
  width: 1200px;
  height: 649px;
}
</style>
